# Generated by Django 5.2 on 2025-05-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startup_closed_year_startup_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='lessons_learned',
            field=models.TextField(blank=True, null=True),
        ),
    ]
