# Generated by Django 5.2 on 2025-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0004_startup_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
